% Open a plot of the filter coefficients generated by gen_filter_coeffs.m
% in a new window.
source gen_filter_coeffs.m

% Plot filter.
freqz(coeffs, 1, 512, oversampling_rate)
drawnow()
% Wait for plot to be closed before exiting.
uiwait()
