% Print the filter coefficients generated by gen_filter_coeffs.m 
% to standard out in C syntax as a constant array of single precision 32-bit floats.
source gen_filter_coeffs.m

printf("/*\n")
printf(" * This file was automatically generated by the print_filter_coeffs.m octave script.\n")
printf(" * See that file along with gen_filter_coeffs.m for more info.\n")
printf(" */\n")
printf("#include <arm_math_types.h>\n")
printf("\n")
printf("const float32_t filter_coefficients[NR_TAPS] = {\n")
% Reverse coefficients because arm_fir_init_*() requires them in time reversed order. 
coeffs = fliplr(coeffs);
% Print coefficients. 
% The 9 is FLT_DECIMAL_DIG from float.h. See its documentation for more info.
printf("\t%.9g, %.9g, %.9g, %.9g, %.9g,\n", coeffs)
% Put the closing brace on its own line in case the last row of coeffs didn't 
% print a newline.
ncoeff_columns = 5;
if (mod(length(coeffs), ncoeff_columns) != 0)
	printf("\n")
endif
printf("};\n")
